name: dartcarwings
description: A library for the Nissan Leaf Carwings API.
version: 0.0.1
homepage: https://bitbucket.org/Tobiaswk/dartcarwings
author: Tobias Westergaard Kjeldsen <tobias@wkjeldsen.dk>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  intl: '^0.15.6'
  http: '^0.11.3+16'

dev_dependencies:
  test: '^0.12.0'
