name: dartcarwings
description: A library for the Nissan Leaf Carwings API.
version: 0.0.1
homepage: https://gitlab.com/tobiaswkjeldsen/dartcarwings
author: Tobias Westergaard Kjeldsen <tobias@wkjeldsen.dk>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  intl: '^0.15.7'
  http: '^0.12.0'

dev_dependencies:
  test: '^1.3.0'
